### ISSUE TITLE
Slide Comments

### ISSUE THREAD

**Issue by JimLynchCodes** [xlozinguez/angular-nyc-advanced-ngrx#2]
Some suggestions for the slides. I couldn't figure out how to to something like "track changes", and I didn't want to just make the changes without you knowing about them so I'm just listing my suggestions here:

- On slide 6: change "Action" to "Actions".
- Slide 7 - change "take" to "use". Just sounds better imo to say it like that, "Pure functions _use_ the previous state and the next action to compute the new state."
- Slide 10 - third bullet should say "Actions" with an "s"? Or if you really are only talking about 1 action then change it "Action are dispatched" to "Action is dispatched"
 - In fourth bullet, if you decide to go plural for third bullet then change action’s to actions'. 
- Slide 11 - I really like this diagram. lol
- Slide 26 - "Separation of concerns, selectors handle the state composition to..." 
Sounds weird. Maybe change the initial part to describe the word "selectors". Something like this:
 "Separating concerns, selectors handle the state composition to..." 
- Slide 32 - LOL. I know right
- Slide 46 - Is this supposed to be just a blank slide?
![advanced__ngrx_-_google_slides](https://cloud.githubusercontent.com/assets/5354163/22031813/dd1d1896-dcaf-11e6-8d78-b6a44714c663.png)
- Slide 54 - weird little line in the corner:
![advanced__ngrx_-_google_slides](https://cloud.githubusercontent.com/assets/5354163/22031866/176c4dfa-dcb0-11e6-8d1a-d34a5255a97f.png)

**Comment by xlozinguez** [comment]
thanks @JimTheMan ;) closing now
